DROP TABLE Café;

-- Kavárna (ID, Název, Adresa, Otevírací hodiny, Kapacita míst, Popis)
CREATE TABLE Café 
(
	CaféID NUMBER(32) GENERATED BY DEFAULT ON NULL AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	Address VARCHAR2(256) NOT NULL,
	OpenFrom TIMESTAMP NOT NULL,
	OpenTo TIMESTAMP NOT NULL,
	Capacity NUMBER(32) NOT NULL,
	Description VARCHAR2(4000) NULL,

	CONSTRAINT CaféPK PRIMARY KEY (CaféID),
	CONSTRAINT TimesNotOverlaping CHECK (OpenFrom < OpenTo)
);

-- Uživatel (ID, Jméno, E-mail, Oblíbený druh přípravy, Vypitých káv denně)


-- Zaměstnanec (ID, Jméno, Pracovní pozice)


-- Recenze (ID, Text recenze, Počet hvězdiček, Datum návštěvy)


-- Reakce (ID, Text reakce, Datum, Počet palců nahoru, Počet palců dolů)


-- Druh kávy (ID, Název, Oblast původu, Kvalita, Popis, Standardní cena)


-- Kávová zrna (ID, Odrůda, Stupeň kyselosti, Aroma, Chuť)


-- Cupping akce (ID, Název, Datum konání, Počet volných míst)



INSERT INTO Café (Name, Address, OpenFrom, OpenTo, Capacity)
VALUES
(
	'Mr. Nováks Super Coffee',
	'Nějaká 23, Brno',
	TO_TIMESTAMP('06:00','hh24:mi'),
	TO_TIMESTAMP('20:00','hh24:mi'),
	66
);
