DROP TABLE Reactions;
DROP TABLE Reviews;
DROP TABLE CuppingEventAttendees;
DROP TABLE CuppingEventTastings;
DROP TABLE CuppingEvents;
DROP TABLE Employees;
DROP TABLE Users;
DROP TABLE CoffeeBeansMixture;
DROP TABLE CoffeeBeans;
DROP TABLE CaféServesCoffee;
DROP TABLE CoffeeKinds;
DROP TABLE Cafés;

-- Kavárna (ID, Název, Adresa, Otevírací hodiny, Kapacita míst, Popis)
CREATE TABLE Cafés
(
	CaféID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	Address VARCHAR2(256) NOT NULL,
	OpenFrom TIMESTAMP NOT NULL,
	OpenTo TIMESTAMP NOT NULL,
	Capacity NUMBER(32) NOT NULL,
	Description VARCHAR2(4000) NULL,

	CONSTRAINT CaféPK PRIMARY KEY (CaféID),
	CONSTRAINT OpenHoursNotOverlaping CHECK (OpenFrom < OpenTo)
);

-- Druh kávy (ID, Název, Oblast původu, Kvalita, Popis, Standardní cena)
CREATE TABLE CoffeeKinds
(
	CoffeeID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	OriginRegion VARCHAR2(128) NOT NULL,
	Quality NUMBER(32) NOT NULL,
	Description VARCHAR2(4000) NULL,
	StandardPrice NUMBER(32) NOT NULL,

	CONSTRAINT CoffeePK PRIMARY KEY (CoffeeID)
);

-- Vazba: Kavárna nabízí druh kávy
CREATE TABLE CaféServesCoffee
(
	CaféID NUMBER(32) NOT NULL,
	CoffeeID NUMBER(32) NOT NULL,

	CONSTRAINT ServePK PRIMARY KEY (CaféID, CoffeeID),
	CONSTRAINT ServeCaféFK
		FOREIGN KEY (CaféID)
		REFERENCES Cafés (CaféID),
	CONSTRAINT ServeCoffeeFK
		FOREIGN KEY (CoffeeID)
		REFERENCES CoffeeKinds (CoffeeID)
);

-- Kávová zrna (ID, Odrůda, Stupeň kyselosti, Aroma, Chuť)
CREATE TABLE CoffeeBeans
(
	BeanID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Variety VARCHAR2(128) NOT NULL,
	Acidity VARCHAR2(256) NULL,
	Aroma VARCHAR2(256) NULL,
	Flavor VARCHAR(512) NULL,

	CONSTRAINT BeanPK PRIMARY KEY (BeanID)
);

-- Vazba: Druh kávy je složen ze směsi
CREATE TABLE CoffeeBeansMixture
(
	CoffeeID NUMBER(32) NOT NULL,
	BeanID NUMBER(32) NOT NULL,

	CONSTRAINT MixturePK PRIMARY KEY (CoffeeID, BeanID),
	CONSTRAINT MixtureCoffeeFK
		FOREIGN KEY (CoffeeID)
		REFERENCES CoffeeKinds (CoffeeID),
	CONSTRAINT MixtureBeanFK
		FOREIGN KEY (BeanID)
		REFERENCES CoffeeBeans (BeanID)
);

-- Uživatel (ID, Jméno, E-mail, Oblíbený druh přípravy, Vypitých káv denně)
CREATE TABLE Users
(
	UserID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	Email VARCHAR2(64) NOT NULL,
	DailyCoffees NUMBER(32) NOT NULL,
	FavouriteCoffeeKindID NUMBER(32) NULL,
	FavouriteCaféID NUMBER(32) NULL,

	CONSTRAINT UserPK PRIMARY KEY (UserID),
	CONSTRAINT FavCoffeeFK
		FOREIGN KEY (FavouriteCoffeeKindID)
		REFERENCES CoffeeKinds (CoffeeID),
	CONSTRAINT FavCaféFK
		FOREIGN KEY (FavouriteCaféID)
		REFERENCES Cafés (CaféID)
);

-- Zaměstnanec (ID, Jméno, Pracovní pozice)
CREATE TABLE Employees
(
	EmployeeID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	JobOccupation VARCHAR2(128) NOT NULL,
	CaféID NUMBER(32) NULL,

	CONSTRAINT EmployeePK PRIMARY KEY (EmployeeID),
	CONSTRAINT EmployeeCaféFK
		FOREIGN KEY (CaféID)
		REFERENCES Cafés (CaféID)
);

-- Cupping akce (ID, Název, Datum konání, Počet volných míst)
CREATE TABLE CuppingEvents
(
	CuppingEventID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	EventDate DATE NOT NULL,
	Vacancies NUMBER(32) NOT NULL,
	CaféID NUMBER(32) NOT NULL,

	CONSTRAINT CuppingEventPK PRIMARY KEY (CuppingEventID),
	CONSTRAINT CuppingEventCaféFK
		FOREIGN KEY (CaféID)
		REFERENCES Cafés (CaféID)
);

-- Vazba: Ochutnávka druhu kávy na Cupping akci (Cena ochutnávky)
CREATE TABLE CuppingEventTastings
(
	CuppingEventID NUMBER(32) NOT NULL,
	CoffeeID NUMBER(32) NOT NULL,
	TastingPrice NUMBER(32) NULL,

	CONSTRAINT TastingPK PRIMARY KEY (CuppingEventID, CoffeeID),
	CONSTRAINT TastingCuppingEventFK
		FOREIGN KEY (CuppingEventID)
		REFERENCES CuppingEvents (CuppingEventID),
	CONSTRAINT TastingCoffeeFK
		FOREIGN KEY (CoffeeID)
		REFERENCES CoffeeKinds (CoffeeID)
);

-- Vazba: Uživatelé se učastní cupping akce
CREATE TABLE CuppingEventAttendees
(
	CuppingEventID NUMBER(32) NOT NULL,
	UserID NUMBER(32) NOT NULL,

	CONSTRAINT AttendeePK PRIMARY KEY (CuppingEventID, UserID),
	CONSTRAINT AttendeeCuppingEventFK
		FOREIGN KEY (CuppingEventID)
		REFERENCES CuppingEvents (CuppingEventID),
	CONSTRAINT AttendeeUserFK
		FOREIGN KEY (UserID)
		REFERENCES Users (UserID)
);

-- Recenze (ID, Text recenze, Počet hvězdiček, Datum návštěvy)
CREATE TABLE Reviews
(
	ReviewID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Text VARCHAR2(4000) NOT NULL,
	Stars NUMBER(1) NOT NULL,
	VisitDate DATE NOT NULL,
	UserID NUMBER(32) NOT NULL,
	CaféID NUMBER(32),
	CuppingEventID NUMBER(32),

	CONSTRAINT ReviewPK PRIMARY KEY (ReviewID),
	CONSTRAINT ReviewerUserFK
		FOREIGN KEY (UserID)
		REFERENCES Users (UserID),
	CONSTRAINT ReviewedCaféFK
		FOREIGN KEY (CaféID)
		REFERENCES Cafés (CaféID),
	CONSTRAINT StarsLimit CHECK (Stars >= 0 AND Stars <= 5),
	CONSTRAINT OneReviewedEntity
		CHECK ((CaféID IS NOT NULL AND CuppingEventID IS NULL)
		       OR (CuppingEventID IS NOT NULL AND CaféID IS NULL))
);

-- Reakce (ID, Text reakce, Datum, Počet palců nahoru, Počet palců dolů)
CREATE TABLE Reactions
(
	ReactionID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Text VARCHAR2(4000) NOT NULL,
	WritenDate DATE NOT NULL,
	ThumbsUp NUMBER(32) NOT NULL,
	ThumbsDown NUMBER(32) NOT NULL,
	ReviewID NUMBER(32) NOT NULL,
	UserID NUMBER(32),
	EmployeeID NUMBER(32),

	CONSTRAINT ReactionPK PRIMARY KEY (ReactionID),
	CONSTRAINT ReactionToReviewFK
		FOREIGN KEY (ReviewID)
		REFERENCES Reviews (ReviewID),
	CONSTRAINT ReactingUserFK
		FOREIGN KEY (UserID)
		REFERENCES Users (UserID),
	CONSTRAINT ReactingEmployeeFK
		FOREIGN KEY (EmployeeID)
		REFERENCES Employees (EmployeeID),
	CONSTRAINT OneReviewer
		CHECK ((UserID IS NOT NULL AND EmployeeID IS NULL)
		       OR (EmployeeID IS NOT NULL AND UserID IS NULL))
);


-- Příkladová data
--INSERT INTO Cafés (Name, Address, OpenFrom, OpenTo, Capacity)
--VALUES
--(
--	'Mr. Nováks Super Coffee',
--	'Nějaká 23, Brno',
--	TO_TIMESTAMP('06:00','hh24:mi'),
--	TO_TIMESTAMP('20:00','hh24:mi'),
--	66
--);
