DROP TABLE Reactions;
DROP TABLE Reviews;
DROP TABLE CuppingEventAttendees;
DROP TABLE CuppingEventTastings;
DROP TABLE CuppingEvents;
DROP TABLE Employees;
DROP TABLE Users;
DROP TABLE CoffeeBeansMixture;
DROP TABLE CoffeeBeans;
DROP TABLE CaféServesCoffee;
DROP TABLE CoffeeKinds;
DROP TABLE Cafés;

-- Kavárna (ID, Název, Adresa, Otevírací hodiny, Kapacita míst, Popis)
CREATE TABLE Cafés
(
	CaféID NUMBER(32) NULL,
	Name VARCHAR2(128) NOT NULL,
	Address VARCHAR2(256) NOT NULL,
	OpenFrom TIMESTAMP NOT NULL,
	OpenTo TIMESTAMP NOT NULL,
	Capacity NUMBER(32) NOT NULL,
	Description VARCHAR2(4000) NULL,

	CONSTRAINT CaféPK PRIMARY KEY (CaféID),
	CONSTRAINT OpenHoursNotOverlaping CHECK (OpenFrom < OpenTo)
);

-- Druh kávy (ID, Název, Oblast původu, Kvalita, Popis, Standardní cena)
CREATE TABLE CoffeeKinds
(
	CoffeeID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	OriginRegion VARCHAR2(128) NOT NULL,
	Quality NUMBER(32) NOT NULL,
	Description VARCHAR2(4000) NULL,
	StandardPrice NUMBER(32) NOT NULL,

	CONSTRAINT CoffeePK PRIMARY KEY (CoffeeID)
);

-- Vazba: Kavárna nabízí druh kávy
CREATE TABLE CaféServesCoffee
(
	CaféID NUMBER(32) NOT NULL,
	CoffeeID NUMBER(32) NOT NULL,

	CONSTRAINT ServePK PRIMARY KEY (CaféID, CoffeeID),
	CONSTRAINT ServeCaféFK
		FOREIGN KEY (CaféID)
		REFERENCES Cafés (CaféID),
	CONSTRAINT ServeCoffeeFK
		FOREIGN KEY (CoffeeID)
		REFERENCES CoffeeKinds (CoffeeID)
);

-- Kávová zrna (ID, Odrůda, Stupeň kyselosti, Aroma, Chuť)
CREATE TABLE CoffeeBeans
(
	BeanID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Variety VARCHAR2(128) NOT NULL,
	Acidity VARCHAR2(256) NULL,
	Aroma VARCHAR2(256) NULL,
	Flavor VARCHAR(512) NULL,

	CONSTRAINT BeanPK PRIMARY KEY (BeanID)
);

-- Vazba: Druh kávy je složen ze směsi
CREATE TABLE CoffeeBeansMixture
(
	CoffeeID NUMBER(32) NOT NULL,
	BeanID NUMBER(32) NOT NULL,

	CONSTRAINT MixturePK PRIMARY KEY (CoffeeID, BeanID),
	CONSTRAINT MixtureCoffeeFK
		FOREIGN KEY (CoffeeID)
		REFERENCES CoffeeKinds (CoffeeID),
	CONSTRAINT MixtureBeanFK
		FOREIGN KEY (BeanID)
		REFERENCES CoffeeBeans (BeanID)
);

-- Uživatel (ID, Jméno, E-mail, Oblíbený druh přípravy, Vypitých káv denně)
CREATE TABLE Users
(
	UserID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	Email VARCHAR2(64) NOT NULL,
	DailyCoffees NUMBER(32) NOT NULL,
	FavouriteCoffeeKindID NUMBER(32) NULL,
	FavouriteCaféID NUMBER(32) NULL,

	CONSTRAINT UserPK PRIMARY KEY (UserID),
	CONSTRAINT FavCoffeeFK
		FOREIGN KEY (FavouriteCoffeeKindID)
		REFERENCES CoffeeKinds (CoffeeID),
	CONSTRAINT FavCaféFK
		FOREIGN KEY (FavouriteCaféID)
		REFERENCES Cafés (CaféID)
);



-- Zaměstnanec (ID, Jméno, Pracovní pozice)
CREATE TABLE Employees
(
	EmployeeID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	JobOccupation VARCHAR2(128) NOT NULL,
	CaféID NUMBER(32) NULL,

	CONSTRAINT EmployeePK PRIMARY KEY (EmployeeID),
	CONSTRAINT EmployeeCaféFK
		FOREIGN KEY (CaféID)
		REFERENCES Cafés (CaféID)
);

-- Cupping akce (ID, Název, Datum konání, Počet volných míst)
CREATE TABLE CuppingEvents
(
	CuppingEventID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR2(128) NOT NULL,
	EventDate DATE NOT NULL,
	Vacancies NUMBER(32) NOT NULL,
	CaféID NUMBER(32) NOT NULL,

	CONSTRAINT CuppingEventPK PRIMARY KEY (CuppingEventID),
	CONSTRAINT CuppingEventCaféFK
		FOREIGN KEY (CaféID)
		REFERENCES Cafés (CaféID)
);

-- Vazba: Ochutnávka druhu kávy na Cupping akci (Cena ochutnávky)
CREATE TABLE CuppingEventTastings
(
	CuppingEventID NUMBER(32) NOT NULL,
	CoffeeID NUMBER(32) NOT NULL,
	TastingPrice NUMBER(32) NULL,

	CONSTRAINT TastingPK PRIMARY KEY (CuppingEventID, CoffeeID),
	CONSTRAINT TastingCuppingEventFK
		FOREIGN KEY (CuppingEventID)
		REFERENCES CuppingEvents (CuppingEventID),
	CONSTRAINT TastingCoffeeFK
		FOREIGN KEY (CoffeeID)
		REFERENCES CoffeeKinds (CoffeeID)
);

-- Vazba: Uživatelé se učastní cupping akce
CREATE TABLE CuppingEventAttendees
(
	CuppingEventID NUMBER(32) NOT NULL,
	UserID NUMBER(32) NOT NULL,

	CONSTRAINT AttendeePK PRIMARY KEY (CuppingEventID, UserID),
	CONSTRAINT AttendeeCuppingEventFK
		FOREIGN KEY (CuppingEventID)
		REFERENCES CuppingEvents (CuppingEventID),
	CONSTRAINT AttendeeUserFK
		FOREIGN KEY (UserID)
		REFERENCES Users (UserID)
);

-- Recenze (ID, Text recenze, Počet hvězdiček, Datum návštěvy)
CREATE TABLE Reviews
(
	ReviewID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Text VARCHAR2(4000) NOT NULL,
	Stars NUMBER(1) NOT NULL,
	VisitDate DATE NOT NULL,
	UserID NUMBER(32) NOT NULL,
	CaféID NUMBER(32),
	CuppingEventID NUMBER(32),

	CONSTRAINT ReviewPK PRIMARY KEY (ReviewID),
	CONSTRAINT ReviewerUserFK
		FOREIGN KEY (UserID)
		REFERENCES Users (UserID),
	CONSTRAINT ReviewedCaféFK
		FOREIGN KEY (CaféID)
		REFERENCES Cafés (CaféID),
	CONSTRAINT StarsLimit CHECK (Stars >= 0 AND Stars <= 5),
	CONSTRAINT OneReviewedEntity
		CHECK ((CaféID IS NOT NULL AND CuppingEventID IS NULL)
		       OR (CuppingEventID IS NOT NULL AND CaféID IS NULL))
);

-- Reakce (ID, Text reakce, Datum, Počet palců nahoru, Počet palců dolů)
CREATE TABLE Reactions
(
	ReactionID NUMBER(32) GENERATED BY DEFAULT AS IDENTITY,
	Text VARCHAR2(4000) NOT NULL,
	WritenDate DATE NOT NULL,
	ThumbsUp NUMBER(32) NOT NULL,
	ThumbsDown NUMBER(32) NOT NULL,
	ReviewID NUMBER(32) NOT NULL,
	UserID NUMBER(32),
	EmployeeID NUMBER(32),

	CONSTRAINT ReactionPK PRIMARY KEY (ReactionID),
	CONSTRAINT ReactionToReviewFK
		FOREIGN KEY (ReviewID)
		REFERENCES Reviews (ReviewID),
	CONSTRAINT ReactingUserFK
		FOREIGN KEY (UserID)
		REFERENCES Users (UserID),
	CONSTRAINT ReactingEmployeeFK
		FOREIGN KEY (EmployeeID)
		REFERENCES Employees (EmployeeID),
	CONSTRAINT OneReviewer
		CHECK ((UserID IS NOT NULL AND EmployeeID IS NULL)
		       OR (EmployeeID IS NOT NULL AND UserID IS NULL))
);

-- Generování primárního klíče pro tabulku kaváren
CREATE OR REPLACE TRIGGER CaféPrimaryKeyTrigger
	BEFORE INSERT ON Cafés
	FOR EACH ROW
	DECLARE
		generatedKey NUMBER(32);
	BEGIN
	IF :NEW.CaféID IS NULL
	THEN
		SELECT COALESCE(MAX(CaféID) + 1, 1) INTO generatedKey FROM Cafés;
		:NEW.CaféID := generatedKey;
	END IF;
END CaféPrimaryKeyTrigger;
/

-- Uživatel potvrdí účast na cupping akci, aktualizuje se počet volných míst
-- Nedostatek volných míst => výjimka VALUE_ERROR
CREATE OR REPLACE TRIGGER UserAttendsCuppingEventTrigger
	BEFORE INSERT ON CuppingEventAttendees
	FOR EACH ROW
	DECLARE
		remainingSeats NUMBER(32);
	BEGIN
	SELECT Vacancies INTO remainingSeats
	FROM CuppingEvents
	WHERE CuppingEventID = :NEW.CuppingEventID;

	IF remainingSeats > 0
	THEN
		UPDATE CuppingEvents
		SET Vacancies = remainingSeats - 1
		WHERE CuppingEventID = :NEW.CuppingEventID;
	ELSE
		RAISE VALUE_ERROR;
	END IF;
END UserAttendsCuppingEventTrigger;
/

-- Přidá uživatele jako účastníka na cupping akci
CREATE OR REPLACE PROCEDURE AddCuppingEventAttendee
	(cuppingEventID IN NUMBER,
	userID IN NUMBER) IS
BEGIN
  	INSERT INTO CuppingEventAttendees(CuppingEventID, UserID) VALUES 
	(
		cuppingEventID,
		userID
	);
EXCEPTION
	WHEN VALUE_ERROR THEN
		ROLLBACK;
END AddCuppingEventAttendee;
/


-- Příkladová data
INSERT INTO Cafés (Name, Address, OpenFrom, OpenTo, Capacity, Description) VALUES (
	'Mr. Nováks Super Coffee',
	'Nějaká 23, Brno',
	TO_TIMESTAMP('06:00','hh24:mi'),
	TO_TIMESTAMP('20:00','hh24:mi'),
	66,
	'Na místě bývalé truhlárny jsme vytvořili prostor, který nám chyběl. Netradiční kavárnu, kde najdeš mnohem víc než jen výběrovou kávu, domácí dobroty a skvělé snídaně. Součástí je taky galerie, multifunkční místnost k pronájmu a dvůr, kde pod hvězdami a za doprovodu té správné melodie snadno ztratíš pojem o čase a zapomeneš, že jsi v centru města.'
);
INSERT INTO Cafés (Name, Address, OpenFrom, OpenTo, Capacity, Description) VALUES (
	'Caffé 60',
	'Purcnerova 60, 676 02 Moravské Budějovice',
	TO_TIMESTAMP('08:00','hh24:mi'),
	TO_TIMESTAMP('18:00','hh24:mi'),
	66,
	'Popis kavárny'
);
INSERT INTO Cafés (Name, Address, OpenFrom, OpenTo, Capacity, Description) VALUES (
	'Kavárna Opera',
	'Horní náměstí 21 779 00 Olomouc',
	TO_TIMESTAMP('14:00','hh24:mi'),
	TO_TIMESTAMP('21:00','hh24:mi'),
	66,
	'Jsme tradiční kavárna v samém centru města Olomouce.'
);

INSERT INTO CoffeeKinds (Name, OriginRegion , Quality , Description, StandardPrice ) VALUES (
	'Espresso',
	'Austrálie',
	4,
	'Popis',
	69
);
INSERT INTO CoffeeKinds (Name, OriginRegion , Quality , Description, StandardPrice ) VALUES (
	'Americano',
	'USA',
	4,
	'Káva z Ameriky',
	250
);
INSERT INTO CoffeeKinds (Name, OriginRegion , Quality , Description, StandardPrice ) VALUES (
	'Cappucino',
	'Francie',
	4,
	'Káva z Francie',
	125
);
INSERT INTO CoffeeKinds (Name, OriginRegion , Quality , Description, StandardPrice ) VALUES (
	'Ristretto',
	'Belgie',
	4,
	'Káva z Belgie',
	137
);

INSERT INTO CaféServesCoffee (CaféID,CoffeeID) VALUES (
	1,
	1
);
INSERT INTO CaféServesCoffee (CaféID,CoffeeID) VALUES (
	1,
	2
);
INSERT INTO CaféServesCoffee (CaféID,CoffeeID) VALUES (
	1,
	3
);
INSERT INTO CaféServesCoffee (CaféID,CoffeeID) VALUES (
	2,
	4
);
INSERT INTO CaféServesCoffee (CaféID,CoffeeID) VALUES (
	2,
	1
);
INSERT INTO CaféServesCoffee (CaféID,CoffeeID) VALUES (
	3,
	1
);
INSERT INTO CaféServesCoffee (CaféID,CoffeeID) VALUES (
	3,
	2
);

INSERT INTO CoffeeBeans (Variety  , Acidity  , Aroma , Flavor) VALUES (
	'Bourbon',
	'2',
	'Aroma je kakaové, poznáte v něm cukrovou třtinu i koření.',
	'Kakao, vanilka, koření, oříšky'
);
INSERT INTO CoffeeBeans (Variety  , Acidity  , Aroma , Flavor) VALUES (
	'Typica',
	'3',
	'Aroma je kakaové.',
	'Čokoláda, Ovoce'
);
INSERT INTO CoffeeBeans (Variety  , Acidity  , Aroma , Flavor) VALUES (
	'Bourbon',
	'1',
	'Aroma je ořechové.',
	'Čokoláda, Ořech'
);
INSERT INTO CoffeeBeans (Variety  , Acidity  , Aroma , Flavor) VALUES (
	'Bourbon',
	'2',
	'Květinové aroma proložené vůní horských bylin.',
	'Ovoce, ořechy, čokoláda'
);


INSERT INTO CoffeeBeansMixture (CoffeeId,BeanId) VALUES (
	1,
	2
);
INSERT INTO CoffeeBeansMixture (CoffeeId,BeanId) VALUES (
	2,
	1
);
INSERT INTO CoffeeBeansMixture (CoffeeId,BeanId) VALUES (
	3,
	4
);
INSERT INTO CoffeeBeansMixture (CoffeeId,BeanId) VALUES (
	4,
	3
);

INSERT INTO Users (Name, Email  , DailyCoffees  , FavouriteCoffeeKindID , FavouriteCaféID) VALUES (
	'Michal Rivola',
	'xrivol01@fit.vutbr.cz',
	0,
	2,
	2
);
INSERT INTO Users (Name, Email  , DailyCoffees  , FavouriteCoffeeKindID , FavouriteCaféID) VALUES (
	'Lubor Kříž',
	'lubor@seznam.cz',
	10,
	2,
	3
);
INSERT INTO Users (Name, Email  , DailyCoffees  , FavouriteCoffeeKindID , FavouriteCaféID) VALUES (
	'Benjamin Flores',
	'benjamin@google.com',
	5,
	3,
	1
);

INSERT INTO Employees (Name, JobOccupation  , CaféID) VALUES (
	'Jose Hickman',
	'Majitel',
	1
);

INSERT INTO Employees (Name, JobOccupation  , CaféID) VALUES (
	'Cara Berger',
	'Majitel',
	2
);

INSERT INTO Employees (Name, JobOccupation  , CaféID) VALUES (
	'Jacqueline Holloway',
	'Majitel',
	3
);

INSERT INTO Employees (Name, JobOccupation  , CaféID) VALUES (
	'Michal Rivola',
	'Manažer',
	2
);
INSERT INTO Employees (Name, JobOccupation  , CaféID) VALUES (
	'Čestmír Jelínek',
	'Uklízeč',
	3
);
INSERT INTO Employees (Name, JobOccupation  , CaféID) VALUES (
	'Stanislava Pospíšilová',
	'Servírka',
	1
);

INSERT INTO CuppingEvents(Name,EventDate,Vacancies , CaféID ) VALUES (
	'Oslava bodů z IDS',
	TO_DATE('10/04/2021','dd/mm/yyyy'),
	1,
	3
);
INSERT INTO CuppingEvents(Name,EventDate,Vacancies , CaféID ) VALUES (
	'Ochutnávka kávy',
	TO_DATE('21/04/2021','dd/mm/yyyy'),
	31,
	2
);


INSERT INTO CuppingEventTastings(CuppingEventID ,CoffeeID ,TastingPrice ) VALUES (
	1,
	2,
	0
);
INSERT INTO CuppingEventTastings(CuppingEventID ,CoffeeID ,TastingPrice ) VALUES (
	2,
	3,
	45
);

-- Cupping akce 1 má kapacitu míst 1
-- Uživatel 1 je přidán v tabulce CuppingEventAttendees
EXEC AddCuppingEventAttendee(cuppingEventID => 1, userID => 1);
-- Kapacita cupping akce 1 je nyní 0, neumožní přidání dalších účastníku

-- Nepřidá se vyhodí výjimku
EXEC AddCuppingEventAttendee(cuppingEventID => 1, userID => 3);

-- Nepřidá se vyhodí výjimku
EXEC AddCuppingEventAttendee(cuppingEventID => 1, userID => 2);

-- Cupping akce 2 má kapacitu 31
EXEC AddCuppingEventAttendee(cuppingEventID => 2, userID => 2);
EXEC AddCuppingEventAttendee(cuppingEventID => 2, userID => 1);
-- Účastníci vložení, kapacita cupping akce 2 je nyní 29

INSERT INTO Reviews(Text ,Stars , VisitDate ,  UserID ,CaféID , CuppingEventID ) VALUES (
	'Úžasné',
	5,
	TO_DATE('10/04/2021','dd/mm/yyyy'),
	2,
	'',
	1
);
INSERT INTO Reviews(Text ,Stars , VisitDate ,  UserID ,CaféID , CuppingEventID ) VALUES (
	'Ušlo to',
	3,
	TO_DATE('21/04/2021','dd/mm/yyyy'),
	3,
	2,
	''
);
INSERT INTO Reviews(Text ,Stars , VisitDate ,  UserID ,CaféID , CuppingEventID ) VALUES (
	'Mizerná obsluha, kafe i prostředí',
	1,
	TO_DATE('21/04/2021','dd/mm/yyyy'),
	1,
	'',
	2
);

INSERT INTO Reviews(Text ,Stars , VisitDate ,  UserID ,CaféID , CuppingEventID ) VALUES (
	'NOT GREAT NOT TERRIBLE',
	2,
	TO_DATE('18/04/2021','dd/mm/yyyy'),
	1,
	2,
	''
);
INSERT INTO Reviews(Text ,Stars , VisitDate ,  UserID ,CaféID , CuppingEventID ) VALUES (
	'Už sem zažil i lepší',
	2,
	TO_DATE('21/04/2021','dd/mm/yyyy'),
	1,
	1,
	''
);
INSERT INTO Reviews(Text ,Stars , VisitDate ,  UserID ,CaféID , CuppingEventID ) VALUES (
	'Radši mám cukrárnu',
	4,
	TO_DATE('21/04/2021','dd/mm/yyyy'),
	1,
	2,
	''
);


INSERT INTO Reactions(Text, WritenDate ,ThumbsUp,ThumbsDown, ReviewID  ,UserID  , EmployeeID  )
VALUES
(
	'Děkujeme, snad nás brzy zase navštívíte',TO_DATE('25/04/2021','dd/mm/yyyy'),1,1,1,'',2
);
INSERT INTO Reactions(Text, WritenDate ,ThumbsUp,ThumbsDown, ReviewID  ,UserID  , EmployeeID  )
VALUES
(
	'To nás mrzí, do příště to zkusíme vylepšit',TO_DATE('25/04/2021','dd/mm/yyyy'),1,0,3,'',2
);


-- Cena ochutnávky kávy na cupping akci 'Oslava bodů z IDS' a běžná cena.
SELECT CuppingEvents.Name, CoffeeKinds.Name, CuppingEventTastings.TastingPrice, CoffeeKinds.StandardPrice
FROM CuppingEvents
NATURAL JOIN CuppingEventTastings
JOIN CoffeeKinds ON CoffeeKinds.CoffeeID = CuppingEventTastings.CoffeeID
WHERE CuppingEventId =
(
	SELECT DISTINCT CuppingEvents.CuppingEventID
	FROM CuppingEvents
	WHERE CuppingEvents.Name = 'Oslava bodů z IDS'
);

-- Uživatelé, kteří napsali recenzi
SELECT Users.Name, Reviews.Text, Reviews.Stars
FROM Users NATURAL JOIN Reviews;

-- Jména a příjmení; a pozice zaměstanců kavárny 'Caffé 60'
SELECT Employees.Name, Employees.JobOccupation
FROM Employees JOIN Cafés ON Employees.CaféID = Cafés.CaféID
WHERE Employees.CaféID =
(
	SELECT DISTINCT Cafés.CaféID
	FROM Cafés
	WHERE Cafés.Name = 'Caffé 60'
);

-- Druh kávy podle kávových zrn
SELECT CoffeeKinds.Name, CoffeeBeans.Variety
FROM CoffeeKinds 
NATURAL JOIN CoffeeBeansMixture
NATURAL JOIN CoffeeBeans;

-- Počty zaměstanců na určitých pracovních pozicích.
SELECT COUNT(EmployeeID), JobOccupation
FROM Employees
GROUP BY JobOccupation;

-- Počet recenzí na kavárnu a její průměrné hodnocení. 
SELECT Name, COUNT(ReviewID) TotalReviews, AVG(Stars) AverageStars
FROM
(
	SELECT Cafés.Name, Reviews.ReviewID, Reviews.Stars
	FROM Cafés NATURAL LEFT JOIN Reviews
)
GROUP BY Name;

-- Všechny kavárny, které nemají žádné recenze.
SELECT CaféID, Name
FROM Cafés
WHERE NOT EXISTS
(
	SELECT * FROM Reviews 
	WHERE Reviews.CaféID = Cafés.CaféID
);

-- Používané druhy káv v kavárnách 'Caffé 60' a 'Kavárna opera'
SELECT DISTINCT CoffeeKinds.Name, Cafés.Name
FROM CoffeeKinds
JOIN CaféServesCoffee ON CoffeeKinds.CoffeeID = CaféServesCoffee.CoffeeID
JOIN Cafés ON CaféServesCoffee.CaféID = Cafés.CaféID
WHERE Cafés.Name IN
(
	SELECT Name FROM Cafés
	WHERE Name = 'Caffé 60' OR Name = 'Kavárna Opera'
);

